---
title: "Start-up message"
output: html_document
date: "2022-12-27"
---

## Code
Add this code to your R package under `R/zzz.R`

```{r}
#' Add a random tip of the day
#' @description Tip is disabled if the user has options(<pkg>.quiet = TRUE)
#' in their .Rprofile
#'
#' @param libname required with .onAttach()
#' @param pkgname required with .onAttach()
#' @noRd
.onAttach <- function(libname, pkgname) {
  # look at https://github.com/tidyverse/ggplot2/blob/main/R/zzz.r
  if (!interactive() || isTRUE(getOption(paste0(pkgname, "quiet"))) {
    return()
  }
  
  random_tip(pkg = pkgname)
}

#' Helper function to generate a random greeting
#' @param time timestamp used to pick correct greeting
#' @importFrom dplyr case_when
#' @noRd
#' @examples random_greeting()
random_greeting <- function(time = Sys.time()) {
  hour <- as.POSIXlt(time)$hour

  greeting <-
    case_when(
      hour < 5 | hour >= 21 ~  "\U0001f44b Hi there!",
      hour < 12 ~ "\U0001f31e Good morning!",
      hour < 17 ~ "\U0001f31e Good afternoon!",
      hour < 21 ~ "\U0001f31c Good evening!"
    )

  closing <-
    c(
      "Have a great day rockstar \U0001f3b8",
      "Have a great day superstar \U00002728",
      "Have a great day friend \U0001f600",
      "Have a great day coding wizard \U0001f9d9",
      "Have a fantastical day \U0001f9dc"
    )

  # use modulo with 1-index (instead of 0-index)
  closer_id <- (as.integer(time) %% length(closing)) + 1

  list(
    hi = greeting,
    bye = closing[closer_id]
  )
}


#' Helper function to provide random tip
#' @param pkg the name of the package
#' @importFrom dplyr as_tibble select filter group_by summarise sample_n
#' @importFrom glue glue glue_collapse
#' @importFrom stringr str_wrap
#' @importFrom cli style_bold col_br_black col_br_cyan col_br_magenta cli_text
#' @noRd
random_tip <- function(pkg) {
  msg <- random_greeting()
  x <- help.search("*", package = pkg)
  entries <-as_tibble(x$matches)
  topics <-
    entries |>
    select(-LibPath) |>
    #filter(grepl("spc", x = Topic)) |>
    filter(Field == "alias") |>
    filter(Entry %in% getNamespaceExports(pkg))


  # ensure random function is selected
  set.seed(as.integer(Sys.time()))

  topic_info <-
    topics |>
    group_by(Topic, Title) |>
    summarise(
      fns =
        glue(cli::style_bold("{Entry}()")) |>
        glue_collapse(" | "),
      .groups = "drop"
    )

  topic_info |>
    sample_n(1) |>
    as.list() |>
    glue_data(
      "[border]
      [msg$hi] Here is today's [bold('[pkg]')] topic:

      [cyan('[fns]')]

      [Title]

      See \\
      [cyan('{.fun [pkg]::[Topic]}')] \\
      to learn more

      [msg$bye]
      [border]
      [black('Turn off message with')] [cyan('options([pkg].quiet = TRUE)')]
      ",
      .trim = TRUE,
      .open = "[",
      .close = "]",
      border = rep("-", getOption("width")) |> paste(collapse = ""),
      black = \(x) cli::col_br_black(glue(x, .open = "[",  .close = "]")),
      bold = \(x) cli::style_bold(glue(x, .open = "[",  .close = "]")),
      cyan = \(x) cli::col_br_cyan(glue(x, .open = "[",  .close = "]")),
      magenta = \(x) cli::col_br_magenta(glue(x, .open = "[",  .close = "]"))
    ) |>
    cli::cli_text() |> # interprets {.fun} to open help menu
    packageStartupMessage() # suppressible by suppressPackageStartupMessages
}

```

Here is what the output looks like. Inside your package, the `pkgname` argument will automatically use your package inside `.onAttach()`

```{r}
random_tip("headliner")
```
-----------------------------------------------------------------------------------------------------------------------------------------
🌞 Good morning! Here is today's headliner topic:

demo_data()

Small data set referencing the current date

See `headliner::demo_data()` to learn more

Have a great day rockstar 🎸
-----------------------------------------------------------------------------------------------------------------------------------------
Turn off message with options(headliner.quiet = TRUE)

```{r}
random_tip("ggplot2")
```
-----------------------------------------------------------------------------------------------------------------------------------------
🌞 Good morning! Here is today's ggplot2 topic:

position_stack() | position_fill()

Stack overlapping objects on top of each another

See `ggplot2::position_stack()` to learn more

Have a fantastical day 🧜
-----------------------------------------------------------------------------------------------------------------------------------------
Turn off message with options(ggplot2.quiet = TRUE)

## Testing
The `testthat` package will already be loaded
```{r}
test_that("random greetings are based on time of day", {
  times <-
    as.POSIXct("2023-01-01 00:00:00") +
    lubridate::hours(0:23) +
    lubridate::seconds(0:23)

  all_statements <- random_greeting(times)
  expect_equal(length(unique(all_statements$hi)), 4)
  expect_equal(length(unique(all_statements$bye)), 5)
})


test_that("random tip works", {
  expect_message(random_tip("forcats"), "forcats\\.quiet")
  expect_message(random_tip("glue"), "glue\\.quiet")
})
```
