---
title: "waterfall"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(tidyverse)

url_csv <- 
  "https://raw.githubusercontent.com/rjake/CommonFiles/master/waterfall_base_data.csv"


superstore <- 
  read.csv(url_csv, stringsAsFactors = F) %>% 
  select(-Discount) %>% 
  rename(ListPrice = Sales_ifNoDiscount,
         Discount = DiscountValue) %>% 
  filter(Quantity == 1,
         Cost < 150)
```

```{r}
#https://learnr.wordpress.com/2010/05/10/ggplot2-waterfall-charts/

whatHappened <- 
  superstore %>% 
  select(Order, Order.ID, Cost, ListPrice, Discount) %>%
  mutate(Cost = -Cost) %>% 
  gather(key = Event, value = Value, Cost:Discount) %>% 
  mutate(Event = factor(Event, levels = c("Cost", "ListPrice", "Discount"))) %>% 
  arrange(Order) %>% 
  mutate(Order2 = row_number(),
         End = cumsum(Value), 
         Start = lag(End, default = 0)) %>% 
  group_by(Order) %>% 
  mutate(Cost2 = ifelse(Event == "Cost", Start, 
                 ifelse(Event == "ListPrice", lag(Start),
                 ifelse(Event == "Discount", lag(Start, 2), NA)))) %>% 
  ungroup()
```

```{r}

colors <- c("#aba5a5", "#85c5a2", "#ea7e26")

ggplot(whatHappened[1:(3*8),], aes(Order)) + 
  geom_hline(yintercept = 0) +
  geom_rect(aes(x = Order2, fill = Event,
                xmin = Order2 - 0.45, 
                xmax = Order2 + 0.45, 
                ymin = End, 
                ymax = Start)) +
  scale_fill_manual(values = colors) +
  geom_rect(aes(x = Order2,
                xmin = Order2 - 0.47, 
                xmax = Order2 + 0.47, 
                ymin = Cost2,
                ymax = Cost2+1), 
            color = "NA", fill = "black") + 
  ylab("$ of Event") +
  ylim(-210,200) +
  theme_minimal()  +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title = element_blank(),
        axis.ticks.x = element_blank()#
        ,legend.position = "none"
        )

#ggsave(file="ggWaterfall.png", width=4.5, height=3)
```


```{r}
#https://learnr.wordpress.com/2010/05/10/ggplot2-waterfall-charts/

whatHappened2 <- 
  superstore %>% 
  select(Order, Order.ID, Cost, ListPrice) %>%
  mutate(Cost = -Cost) %>% 
  gather(key = Event, value = Value, Cost:ListPrice) %>% 
  mutate(Event = factor(Event, levels = c("Cost", "ListPrice"))) %>% 
  arrange(Order) %>% 
  mutate(Order2 = row_number(),
         End = cumsum(Value), 
         Start = lag(End, default = 0)) %>% 
  group_by(Order) %>% 
  mutate(Cost2 = ifelse(Event == "Cost", Start, 
                 ifelse(Event == "ListPrice", lag(Start), NA))) %>% 
  ungroup()
```

```{r}

ggplot(whatHappened2[1:(2*8),], aes(Order)) + 
  geom_rect(aes(x = Order2, fill = Event,
                xmin = Order2 - 0.45, 
                xmax = Order2 + 0.45, 
                ymin = End, 
                ymax = Start)) +
  scale_fill_manual(values = colors) +
  geom_rect(aes(x = Order2,
                xmin = Order2 - 0.47, 
                xmax = Order2 + 0.47, 
                ymin = Cost2,
                ymax = Cost2+1), 
            color = "NA", fill = "black") + 
  geom_hline(yintercept = 0) +
    ylab("$ of Event") +
  ylim(-210,200) +
  theme_minimal()+
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title = element_blank(),
        axis.ticks.x = element_blank()#
        ,legend.position = "none"
        )

#ggsave(file="ggWaterfall2.png", width=4.5, height=3)
```
